spring:
  datasource:
    url: jdbc:mysql://47.102.128.12:3306/travel
    username: travel
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:static/, file:static/

file:
  maxUploadSizeMB: 10
  savePath: img
server:
  port: 8181

travel:
  constant:
    pageSize: 10
