spring:
  datasource:
    url: jdbc:mysql://${自定义地址}
    username: ${自定义用户名}
    password: ${自定义密码}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:static/, file:static/

file:
  maxUploadSizeMB: 10
  savePath: img
server:
  port: 8181

travel:
  constant:
    pageSize: 10
